#ifndef _FIELD_INITIALIZOR
#define _FIELD_INITIALIZOR
#pragma once

enum FIELD_INITIALIZOR_TYPE
{
	FIT_NONE = 0,
	FIT_VALUE = 1,
	FIT_USERNAME = 2,
	FIT_LOGIN_TEXT = 3,
	FIT_VALUE_OR_LOCKED_TEXT = 4,
	FIT_VALUE_OR_LOGIN_TEXT = 5,
};

struct FIELD_INITIALIZOR
{
	FIELD_INITIALIZOR_TYPE type;
	wchar_t* value;
};

#endif